---
roles:
  - name: geerlingguy.docker
    version: 7.5.5
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.ntp
    version: 3.0.0
  - name: geerlingguy.security
    version: 3.0.0
  - name: hifis.unattended_upgrades
    version: v3.2.0
  - name: grog.package
    version: v1.4.1
  - name: borgbase.ansible_role_borgbackup
    version: v1.1.3
  - name: tibiiius.simple_compose
