---
roles:
  - name: geerlingguy.docker
    version: 7.4.1
  - name: geerlingguy.pip
    version: 3.0.3
  - name: geerlingguy.ntp
    version: 2.5.0
  - name: geerlingguy.security
    version: 2.4.0
  - name: hifis.unattended_upgrades
    version: v3.2.0
  - name: grog.package
    version: v1.4.0
  - name: borgbase.ansible_role_borgbackup
    version: v1.0.1
  - name: tibiiius.simple_compose
