---
- name: Run tasks for all hosts
  hosts: all
  become: true
  roles:
    - role: system
    - role: hifis.unattended_upgrades
      when: ansible_facts['os_family'] == "Debian"
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: docker
    - role: reverse_proxy

- name: Run tasks for mailserver host(s)
  hosts: mailserver
  become: true
  roles:
    - role: mail
