- name: Update packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true

- name: Install base
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: No SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  register: sshd_config

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: sshd_config.changed # noqa: no-handler
