---
- name: Ensure project directory exists
  ansible.builtin.file:
    path: "{{ atuin_project_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Copy project files
  ansible.builtin.template:
    dest: "{{ atuin_project_dir }}/{{ item }}"
    src: "templates/{{ item }}.j2"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0400"
  loop:
    - .env
    - docker-compose.yaml

- name: Bring up compose project
  community.docker.docker_compose_v2:
    project_src: "{{ atuin_project_dir }}"
