pip_install_packages:
  - docker

# Ensures that given users are added to the docker group
docker_users:
  - "{{ username }}"

# Install Compose as a plugin
docker_install_compose_plugin: true
docker_install_compose: false
