---
- name: Configure CoreOS VMs
  hosts: homeserver_cluster
  gather_facts: false
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 600

    - name: Setup user
      ansible.builtin.include_role:
        name: setup_user

    - name: Apply CoreOS tuning
      ansible.builtin.include_role:
        name: coreos_tuning
