---
- name: Deploy k3s cluster
  hosts: homeserver_cluster
  become: true
  vars:
    ansible_user: ansible
  collections:
    - k3s.orchestration
  roles:
    - role: k3s_server
      vars:
        k3s_install_type: server
        k3s_server_init: true