- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install base
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present
