---
- name: Ensure all neccessary groups are created first
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - "{{ username }}"

- name: Create user "{{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ shell }}"
    createhome: true
    password: "{{ userpass }}"
    update_password: always
    groups:
      - sudo
      - "{{ username }}"
    append: true
    state: present

- name: Passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Copy over SSH keys for "{{ username }}"
  ansible.posix.authorized_key:
    key: "{{ item.key }}"
    state: present
    user: "{{ username }}"
    # exclusive does not work with loops
    exclusive: false
    manage_dir: true
  loop: "{{ ssh_keys }}"

- name: Generate SSH keypair for "{{ username }}"
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    comment: "{{ username }}@{{ inventory_hostname }}"
    type: rsa
    size: 4096
    state: present
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Setup dotfiles for "{{ username }}"
  become: true
  become_user: "{{ username }}"
  block:
    - name: Install chezmoi
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
        creates: $HOME/.local/bin/chezmoi
    - name: Install dotfiles from "{{ dotfiles_location }}"
      ansible.builtin.shell:
        cmd: $HOME/.local/bin/chezmoi init --apply "{{ dotfiles_location }}"
        creates: $HOME/.local/share/chezmoi
