---
- name: Run essential Docker tasks
  ansible.builtin.include_tasks: essentials.yaml

- name: Setup Compose projects using tibiiius.simple_compose
  ansible.builtin.import_role:
    name: tibiiius.simple_compose
  when: simple_compose_projects | length > 0
