---
- name: Ensure directories are setup
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Run as user "{{ username }}"
  become: true
  become_user: "{{ username }}"
  block:
    - name: Login to DockerHub
      community.docker.docker_login:
        registry_url: "https://index.docker.io/v2/"
        username: tibilius1337
        password: "{{ dockerhub_password }}"

    - name: Setup watchtower
      community.docker.docker_container:
        name: "watchtower"
        state: started
        image: "docker.io/containrrr/watchtower:latest"
        volumes:
          - "/home/{{ username }}/.docker/config.json:/config.json:ro"
          - "/var/run/docker.sock:/var/run/docker.sock"
        env:
          # Runs every day at 4am (2am UTC)
          WATCHTOWER_SCHEDULE: "0 0 2 * * *"
          WATCHTOWER_CLEANUP: "true"
